server.port=${PORT:8080}

# Java looks for a variable named MONGO_URL
spring.data.mongodb.uri=${MONGO_URL}

# This is correct and keeps things organized
spring.data.mongodb.database=groccompare
logging.level.org.springframework.data.mongodb=DEBUG