server.port=${PORT:8080}

# Railway will provide the full authenticated string here
spring.data.mongodb.uri=${MONGO_URL}

# This tells Spring to use the specific database name we created
spring.data.mongodb.database=${MONGODATABASE}

logging.level.org.springframework.data.mongodb=DEBUG