server.port=${PORT:8080}

# Link to the updated variable with the database name
spring.data.mongodb.uri=${MONGO_PUBLIC_URL}

# Added for stability and logging
spring.data.mongodb.database=groccompare
logging.level.org.springframework.data.mongodb=DEBUG